-- =============================================================================
-- Estafeta — Conference & Meeting Platform
-- Database Migration Script
-- Safe to re-run (idempotent throughout)
-- =============================================================================


-- =============================================================================
-- SECTION 1.1 — CHECK CONSTRAINTS & pg_net EXTENSION
-- =============================================================================

-- Enable the pg_net extension for asynchronous HTTP calls from triggers
CREATE EXTENSION IF NOT EXISTS pg_net;

-- CHECK constraint: profile.categoria
-- Ensures only valid user categories are stored
ALTER TABLE profile
  ADD CONSTRAINT IF NOT EXISTS chk_profile_categoria
  CHECK (categoria IN ('admin', 'producer', 'provider', 'services', 'client'));

-- CHECK constraint: meeting.status
-- Ensures only valid meeting statuses are stored
ALTER TABLE meeting
  ADD CONSTRAINT IF NOT EXISTS chk_meeting_status
  CHECK (status IN ('proposed', 'accepted', 'rejected', 'rescheduled', 'cancelled'));


-- =============================================================================
-- SECTION 1.2 — CREATE notification_log TABLE
-- =============================================================================

-- Stores failed Edge Function notification attempts for observability and retry audits.
-- meeting_id and profile_id are bigint to match the bigint PKs of meeting and profile.
CREATE TABLE IF NOT EXISTS notification_log (
  id            bigint      generated by default as identity not null,
  created_at    timestamptz DEFAULT now(),
  function_name text        NOT NULL,
  recipient     text        NOT NULL,
  error         text        NOT NULL,
  meeting_id    bigint      REFERENCES meeting(id) ON DELETE SET NULL,
  profile_id    bigint      REFERENCES profile(id) ON DELETE SET NULL
);


-- =============================================================================
-- SECTION 1.3 — TRIGGER FUNCTIONS: PROFILE NOTIFICATIONS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- notify_on_new_registration()
-- Fires AFTER INSERT ON profile.
-- Calls the on-new-registration Edge Function via pg_net so the admin is
-- notified of every new pending registration.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_new_registration()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-new-registration',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'profile_id',     NEW.id,
      'email',          NEW.email,
      'categoria',      NEW.categoria,
      'nombre_empresa', NEW.nombre_empresa
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_approval_invite()
-- Fires AFTER UPDATE OF estado ON profile WHERE NEW.estado = 'approved'.
-- Calls the on-approval-invite Edge Function so the approved user receives
-- a magic-link invite email.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_approval_invite()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-approval-invite',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'profile_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_rejection()
-- Fires AFTER UPDATE OF estado ON profile WHERE NEW.estado = 'rejected'.
-- Calls the on-rejection Edge Function so the rejected user is notified.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_rejection()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-rejection',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'profile_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;


-- =============================================================================
-- SECTION 1.4 — TRIGGER FUNCTIONS: MEETING NOTIFICATIONS
-- =============================================================================

-- ---------------------------------------------------------------------------
-- notify_on_meeting_proposed()
-- Fires AFTER INSERT ON meeting WHERE NEW.status = 'proposed'.
-- Notifies the targeted host user of the incoming meeting proposal.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_meeting_proposed()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-meeting-proposed',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'meeting_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_meeting_accepted()
-- Fires AFTER UPDATE OF status ON meeting WHERE NEW.status = 'accepted'.
-- Notifies the other party that the meeting has been accepted.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_meeting_accepted()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-meeting-accepted',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'meeting_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_meeting_rejected()
-- Fires AFTER UPDATE OF status ON meeting WHERE NEW.status = 'rejected'.
-- Notifies the other party that the meeting has been rejected.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_meeting_rejected()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-meeting-rejected',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'meeting_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_meeting_rescheduled()
-- Fires AFTER UPDATE OF status ON meeting WHERE NEW.status = 'rescheduled'.
-- Notifies the other party of the new proposed time.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_meeting_rescheduled()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-meeting-rescheduled',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'meeting_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- notify_on_meeting_cancelled()
-- Fires AFTER UPDATE OF status ON meeting WHERE NEW.status = 'cancelled'.
-- Notifies both parties that the meeting has been cancelled (e.g. due to a
-- conference conflict) and urges them to reschedule.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_on_meeting_cancelled()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_URL') || '/functions/v1/on-meeting-cancelled',
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_FUNCTION_KEY')
    ),
    body    := jsonb_build_object(
      'meeting_id', NEW.id
    )
  );
  RETURN NEW;
END;
$$;


-- =============================================================================
-- SECTION 1.5 — ATTACH TRIGGERS TO TABLES
-- =============================================================================
-- DROP + CREATE used for idempotency since CREATE OR REPLACE TRIGGER requires
-- the trigger to already exist on older Postgres versions. Supabase runs
-- Postgres 15+ so CREATE OR REPLACE TRIGGER is supported, but DROP IF EXISTS
-- first is equally safe and more portable.

-- ---------------------------------------------------------------------------
-- Profile triggers
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS trg_new_registration ON profile;
CREATE TRIGGER trg_new_registration
  AFTER INSERT ON profile
  FOR EACH ROW
  EXECUTE FUNCTION notify_on_new_registration();

DROP TRIGGER IF EXISTS trg_approval_invite ON profile;
CREATE TRIGGER trg_approval_invite
  AFTER UPDATE OF estado ON profile
  FOR EACH ROW
  WHEN (NEW.estado = 'approved')
  EXECUTE FUNCTION notify_on_approval_invite();

DROP TRIGGER IF EXISTS trg_rejection ON profile;
CREATE TRIGGER trg_rejection
  AFTER UPDATE OF estado ON profile
  FOR EACH ROW
  WHEN (NEW.estado = 'rejected')
  EXECUTE FUNCTION notify_on_rejection();

-- ---------------------------------------------------------------------------
-- Meeting triggers
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS trg_meeting_proposed ON meeting;
CREATE TRIGGER trg_meeting_proposed
  AFTER INSERT ON meeting
  FOR EACH ROW
  WHEN (NEW.status = 'proposed')
  EXECUTE FUNCTION notify_on_meeting_proposed();

DROP TRIGGER IF EXISTS trg_meeting_accepted ON meeting;
CREATE TRIGGER trg_meeting_accepted
  AFTER UPDATE OF status ON meeting
  FOR EACH ROW
  WHEN (NEW.status = 'accepted')
  EXECUTE FUNCTION notify_on_meeting_accepted();

DROP TRIGGER IF EXISTS trg_meeting_rejected ON meeting;
CREATE TRIGGER trg_meeting_rejected
  AFTER UPDATE OF status ON meeting
  FOR EACH ROW
  WHEN (NEW.status = 'rejected')
  EXECUTE FUNCTION notify_on_meeting_rejected();

DROP TRIGGER IF EXISTS trg_meeting_rescheduled ON meeting;
CREATE TRIGGER trg_meeting_rescheduled
  AFTER UPDATE OF status ON meeting
  FOR EACH ROW
  WHEN (NEW.status = 'rescheduled')
  EXECUTE FUNCTION notify_on_meeting_rescheduled();

DROP TRIGGER IF EXISTS trg_meeting_cancelled ON meeting;
CREATE TRIGGER trg_meeting_cancelled
  AFTER UPDATE OF status ON meeting
  FOR EACH ROW
  WHEN (NEW.status = 'cancelled')
  EXECUTE FUNCTION notify_on_meeting_cancelled();


-- =============================================================================
-- SECTION 1.6 — SUPABASE REALTIME PUBLICATIONS
-- =============================================================================
-- Adds all three core tables to the supabase_realtime publication so that
-- Angular services (ProfileService, ConferenceService, MeetingService) can
-- receive live INSERT / UPDATE / DELETE events via the Realtime channel.

ALTER PUBLICATION supabase_realtime ADD TABLE profile;
ALTER PUBLICATION supabase_realtime ADD TABLE conference;
ALTER PUBLICATION supabase_realtime ADD TABLE meeting;


-- =============================================================================
-- SECTION 1.7 — RLS POLICIES: profile TABLE
-- =============================================================================

ALTER TABLE profile ENABLE ROW LEVEL SECURITY;

-- SELECT: users see only their own row; admins see all rows;
-- anonymous users can see pending profiles (user_id IS NULL) so the login
-- form can distinguish "not registered" from "pending approval".
-- Once the invite is generated and user_id is linked, the row is no longer
-- visible to anonymous users — only to the authenticated owner.
DROP POLICY IF EXISTS profile_select ON profile;
CREATE POLICY profile_select ON profile
  FOR SELECT
  USING (
    (user_id = auth.uid())
    OR ((auth.jwt() -> 'app_metadata' ->> 'categoria') = 'admin')
    OR (user_id IS NULL)
  );

-- INSERT: open to unauthenticated requests so new users can self-register
DROP POLICY IF EXISTS profile_insert ON profile;
CREATE POLICY profile_insert ON profile
  FOR INSERT
  WITH CHECK (true);

-- UPDATE: users update only their own row; admins can update any row
DROP POLICY IF EXISTS profile_update ON profile;
CREATE POLICY profile_update ON profile
  FOR UPDATE
  USING (
    (user_id = auth.uid())
    OR ((auth.jwt() -> 'app_metadata' ->> 'categoria') = 'admin')
  );

-- DELETE: admins only (used when rejecting a registration)
DROP POLICY IF EXISTS profile_delete ON profile;
CREATE POLICY profile_delete ON profile
  FOR DELETE
  USING (
    (auth.jwt() -> 'app_metadata' ->> 'categoria') = 'admin'
  );


-- =============================================================================
-- SECTION 1.8 — RLS POLICIES: conference AND meeting TABLES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- conference table
-- ---------------------------------------------------------------------------

ALTER TABLE conference ENABLE ROW LEVEL SECURITY;

-- SELECT: public read — conferences are visible to everyone including anon users
DROP POLICY IF EXISTS conference_select ON conference;
CREATE POLICY conference_select ON conference
  FOR SELECT
  USING (true);

-- INSERT: only the authenticated user who will be the speaker
DROP POLICY IF EXISTS conference_insert ON conference;
CREATE POLICY conference_insert ON conference
  FOR INSERT
  WITH CHECK (speaker_id = auth.uid());

-- UPDATE: host users may only edit their own conferences
DROP POLICY IF EXISTS conference_update ON conference;
CREATE POLICY conference_update ON conference
  FOR UPDATE
  USING (speaker_id = auth.uid());

-- DELETE: the owning speaker, or an admin
DROP POLICY IF EXISTS conference_delete ON conference;
CREATE POLICY conference_delete ON conference
  FOR DELETE
  USING (
    (speaker_id = auth.uid())
    OR ((auth.jwt() -> 'app_metadata' ->> 'categoria') = 'admin')
  );

-- ---------------------------------------------------------------------------
-- meeting table
-- ---------------------------------------------------------------------------

ALTER TABLE meeting ENABLE ROW LEVEL SECURITY;

-- SELECT: host, client, or admin can read a meeting row
DROP POLICY IF EXISTS meeting_select ON meeting;
CREATE POLICY meeting_select ON meeting
  FOR SELECT
  USING (
    (speaker_id     = auth.uid())
    OR (participant_id = auth.uid())
    OR ((auth.jwt() -> 'app_metadata' ->> 'categoria') = 'admin')
  );

-- INSERT: only the client (participant) may propose a meeting
DROP POLICY IF EXISTS meeting_insert ON meeting;
CREATE POLICY meeting_insert ON meeting
  FOR INSERT
  WITH CHECK (participant_id = auth.uid());

-- UPDATE: either party (host or client) may update the meeting during negotiation
DROP POLICY IF EXISTS meeting_update ON meeting;
CREATE POLICY meeting_update ON meeting
  FOR UPDATE
  USING (
    (speaker_id     = auth.uid())
    OR (participant_id = auth.uid())
  );
